spring.application.name=PaymentGatewayService
stripe.secretKey=sk_123456789
spring.datasource.url=jdbc:postgresql://localhost:5432/livetalk
spring.datasource.username=postgres
spring.datasource.password=postgres

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/LiveTalk

# RabbitMQ (AMQP)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest